"""Augmenter la longueur de session_id

Revision ID: 196a9a103f5d
Revises: 87ac3f863797
Create Date: 2024-04-07 23:26:59.111124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196a9a103f5d'
down_revision = '87ac3f863797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
