"""Ajout de session_id à Conversation

Revision ID: 87ac3f863797
Revises: 61fd73b0a7e9
Create Date: 2024-04-07 22:55:58.234557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ac3f863797'
down_revision = '61fd73b0a7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
